### PR TITLE
Misc housekeeping

### PR DESCRIPTION
**Pull request by neftaly**
This PR has several tiny changes:
* Replace N2K numerical PGNs with their text aliases (for readability)
* Send heading data over Wifi (for openCPN etc)
* Use `undefined` instead of `42` for humidity value

### CODE REVIEW

**Comment by neftaly** [comment]
#10

**Comment by sarfata** [comment]
Thanks @neftaly ! Looking great!

I will merge this now. The 42% humidity should have been removed a long time ago. We might also remove the temperature because the temperature inside the box is always significantly higher than the temperature outside the box.

I have been doing very significant changes in the `develop` branch and associated PRs (#31 for example). I have not merged yet in master to avoid confusing people but if you are going to do more work on KBox, I would strongly suggest you work from `develop` instead of `master`.

Thanks!

**Comment by neftaly** [comment]
Ok, sweet!

**Comment by neftaly** [comment]
How about using `N2kts_InsideTemperature`? Later hardware could use something like an external BME280.

**Comment by sarfata** [comment]
@neftaly sorry I had missed your message

> How about using N2kts_InsideTemperature? Later hardware could use something like an external BME280.

Because the i70 display only displayed the outside temperature. Very selfish reason ;) This should be inside, I agree and this should be configurable. It's so far off from the actual inside temperature that I think I have stopped sending it anyway.

**Pull request merged**
