### PR TITLE
NMEA0183 for heel, pitch for Expedition & openCPN

### PR DESCRIPTION
**Pull request by ronzeiller**
HEEL + TRIM is also used instead of PTCH and ROLL
(Expedition uses both)

### CODE REVIEW

**Comment by ronzeiller** [comment]
corrected a copy & paste error (was too late yesterday....)

**Comment by ronzeiller** [comment]
I did a wrong way merge in my git. At least there are just 2 files changed:
**SKNMEAVisitor.cpp** with the new NMEA sentence

and this **readme.txt** in the lib folder. When I delete this Platformio is making it again and I do not know how to get rid of it.
Sorry for confusion....

**Comment by sarfata** [comment]
The build is now failing because the tests need to be updated for the new format: https://travis-ci.org/sarfata/kbox-firmware/builds/307693883#L1551

**Comment by sarfata** [comment]
@ronzeiller I updated the tests so it's all good now. I am going to do a "Squash and Merge" to merge this pull-request in only one commit. This way, the extra commits you added and then removed will not appear in the history of the develop branch.

Thanks a lot for pushing this PR.

closes #63

**Pull request merged**
