### PR TITLE
#13 - KBox configuration

### PR DESCRIPTION
**Pull request by sarfata**
Very much a work in progress. There is just unit tests for now. I still need to plug it into the nmea and imu services.

Sharing so you can give me your opinion and thoughts @ronzeiller .

### CODE REVIEW

**Comment by ronzeiller** [comment]
I think I will have to get used to this JSON thing :-)

First view: looks good :thumbsup:
Second view: may be you could rename NMEA_1, NMEAConfig and all sorts of this to something which describes it better, e.g. COM1 and COM2 (as nice computers still have :grin: )
There could be so much more on these interfaces as Seatalk, PCDIN-sentences, input of extern IMU-sensor or other sensors in a binary format or Actisense format output as is recognised by Expedition software and so on....

Then NMEA-naming will belong to special things as Talker-IDs, sentence-IDs, enabling output of sentences....

**Comment by ronzeiller** [comment]
@sarfata
Thought more about this config issue...

I am afraid that this kind of config will be very, very complicated over all.
We will have around 50 to 100 (or even more) different config settings in different classes where somebody has to search where to find what, because it is not clear where a config variable will belong to.

Then this settings will be boolean, strings, arrays or multidimensional arrays and for all of this tests, and functions will be needed.

I know, that my ini-file with it's simple structure is from programers point of view quite ugly, but it is very simple and fast to implement.

I would suggest:

1.  that we first make a collection of variables already needed, all in one class, very easy to overlook and easy to use all over the code.

2. Then complete all needed functions, inputs and outputs on serial and web interfaces that KBox can be practically used on a boat.

3. Then let´s start to work on the data computer (lot's of more settings, constants, boat parameters, calibration values,.......)

4. And then, at least, when all of this usefull things are working, start a web based configuration thing with this kind of classes, JSON, get set.....

Just my 2cents....

**Comment by sarfata** [comment]
> Second view: may be you could rename NMEA_1, NMEAConfig and all sorts of this to something which describes it better, e.g. COM1 and COM2 (as nice computers still have 😁 )

That is a very good point and I have renamed the config and the service to "SerialService" which should be more generic.

> I am afraid that this kind of config will be very, very complicated over all.
> We will have around 50 to 100 (or even more) different config settings in different classes where somebody has to search where to find what, because it is not clear where a config variable will belong to.

The idea with my system is that each service has one associated configuration class. The reason for doing this is it limits interdependencies between services. The SerialService for example, only knows about SerialConfig, not about the config required for other services.

I hope it will not be too complicated but I understand your concerns and so I have decided to push this PR a bit further and implement a few more config variables, and plug them in the code to see what it looks like. Let's re-discuss when I am done and see if it's too verbose for what it gives us.

> Then this settings will be boolean, strings, arrays or multidimensional arrays and for all of this tests, and functions will be needed.

If we are reading from a INI file we still have to convert to bools, ints, enums or arrays, no? And if we are doing this type of parsing, I think we still need unit tests. I am not sure the choice of JSON or INI changes anything here. Can you explain why INI makes this easier?

**Comment by ronzeiller** [comment]
> If we are reading from a INI file we still have to convert to bools, ints, enums or arrays, no? And if we are doing this type of parsing, I think we still need unit tests. I am not sure the choice of JSON or INI changes anything here. Can you explain why INI makes this easier?

What I meant is, that for implementing new values it is very easy, just write into the according section of **one central** file `xy = nn;` or `xy = array{a,b,c}` and ready you are :)

> The idea with my system is that each service has one associated configuration class. The reason for doing this is it limits interdependencies between services. The SerialService for example, only knows about SerialConfig, not about the config required for other services.

I see your point.
Just thinking of the future where lot of inputs/outputs and data formats will be implemented that it could be that too much encapsulation will make it difficult to read code. and find where, what is.
But as you said: Let's re-discuss it when it becomes more visible where it is going to.

**Comment by ronzeiller** [comment]
Apropos easy.... :-)

Could you please do the special string thing into the Generator for the SignalK Time variable, whenever you find time for this? [85#issueComment](https://github.com/sarfata/kbox-firmware/issues/85#issuecomment-348402690)
Then I could start with the KBox time and the timestamp for logging files....

**Comment by sarfata** [comment]
@ronzeiller would you mind taking one more look and let me know if you see anything wrong?

I will continue working on configuring the WiFi mode, SSID and Password in a separate PR.

**Comment by ronzeiller** [comment]
@sarfata 
This is a huge and great step forward! 
So glad that you took the efford of doing this.
I cannot see anything wrong.
 :thumbsup:  :thumbsup:

**Comment by sarfata** [comment]
closes #13 
closes #71 
closes #62 
closes #43

**Pull request merged**
